# Generated by Django 3.0.5 on 2020-04-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='책의 언어를 입력하세요(e.g English, French, Korean etc.)', max_length=200)),
            ],
        ),
    ]
